//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_thu_cung_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dog
    {
        public int id { get; set; }
        public string name { get; set; }
        public string breed { get; set; }
        public Nullable<int> age { get; set; }
        public Nullable<int> trang_chu_id { get; set; }
    
        public virtual trang_chu trang_chu { get; set; }
    }
}
