//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_thu_cung_.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cat> cats { get; set; }
        public virtual DbSet<dog> dogs { get; set; }
        public virtual DbSet<gioi_thieu> gioi_thieu { get; set; }
        public virtual DbSet<lien_he> lien_he { get; set; }
        public virtual DbSet<phu_kien> phu_kien { get; set; }
        public virtual DbSet<thuc_pham> thuc_pham { get; set; }
        public virtual DbSet<trang_chu> trang_chu { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
